spring:
  application:
    name: music90slibrary
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_library?useTimezone=true&serverTimezone=UTC
    username: USER
    password: PASSWORD
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false
      open-in-view: false
logging:
  level:
    root: warn
    org.flyway: info